(in-package :boa-editor)

(defclass floor-type ()
  ((name :initarg :name :accessor name)
   (which-sheet :initarg :which-sheet :accessor which-sheet)
   (which-icon :initarg :which-icon :accessor which-icon)
   (icon-adjust :initarg :icon-adjust :accessor icon-adjust)
   (ed-icon-adjust :initarg :ed-icon-adjust :accessor ed-icon-adjust)
   (ed-which-sheet :initarg :ed-which-sheet :accessor ed-which-sheet)
   (ed-which-icon :initarg :ed-which-icon :accessor ed-which-icon)
   (blocked :initarg :blocked :accessor blocked :initform 0)
   (step-sound :initarg :step-sound :accessor step-sound :initform -1)
   (light-radius :initarg :light-radius :accessor light-radius :initform 0)
   (floor-height-pixels :initarg :floor-height-pixels :accessor floor-height-pixels :initform 0)
   (special-property :initarg :special-property :accessor special-property :initform 0)
   (special-strength :initarg :special-strength :accessor special-strength :initform 0)
   (is-water :initarg :is-water :accessor is-water :initform 0)
   (is-floor :initarg :is-floor :accessor is-floor :initform 0)
   (is-ground :initarg :is-ground :accessor is-ground :initform 0)
   (is-rough :initarg :is-rough :accessor is-rough :initform 0)
   (fly-over :initarg :fly-over :accessor fly-over :initform 0)
   (shortcut-key :initarg :shortcut-key :accessor shortcut-key)
   (anim-steps :initarg :anim-steps :accessor anim-steps :initform 0)
   (shimmers :initarg :shimmers :accessor shimmers :initform 0)
   (out-fight-town-used :initarg :out-fight-town-used :accessor out-fight-town-used :initform 0)))

(defclass terrain ()
  ((name :initarg :name :accessor name)
   (default-script :initarg :default-script :accessor default-script :initform "Unused")
   (which-sheet :initarg :which-sheet :accessor which-sheet)
   (which-icon :initarg :which-icon :accessor which-icon)
   (icon-adjust :initarg :icon-adjust :accessor icon-adjust)
   (ed-which-sheet :initarg :ed-which-sheet :accessor ed-which-sheet)
   (ed-which-icon :initarg :ed-which-icon :accessor ed-which-icon)
   (cutaway-which-sheet :initarg :cutaway-which-sheet :accessor cutaway-which-sheet :initform -1)
   (cutaway-which-icon :initarg :cutaway-which-icon :accessor cutaway-which-icon)
   (cutaway-icon-adjust :initarg :cutaway-icon-adjust :accessor cutaway-icon-adjust)
   (icon-offset-x :initarg :icon-offset-x :accessor icon-offset-x :initform 0)
   (icon-offset-y :initarg :icon-offset-y :accessor icon-offset-y :initform 0)
   (second-icon :initarg :second-icon :accessor second-icon :initform -1)
   (second-icon-offset-x :initarg :second-icon-offset-x :accessor second-icon-offset-x :initform 0)
   (second-icon-offset-y :initarg :second-icon-offset-y :accessor second-icon-offset-y :initform 0)
   (cutaway-second-icon :initarg :cutaway-second-icon :accessor cutaway-second-icon :initform -1)
   (anim-steps :initarg :anim-steps :accessor anim-steps)
   (move-block-n :initarg :move-block-n :accessor move-block-n :initform 0)
   (move-block-w :initarg :move-block-w :accessor move-block-w :initform 0)
   (move-block-s :initarg :move-block-s :accessor move-block-s :initform 0)
   (move-block-e :initarg :move-block-e :accessor move-block-e :initform 0)
   (look-block-n :initarg :look-block-n :accessor look-block-n :initform 0)
   (look-block-w :initarg :look-block-w :accessor look-block-w :initform 0)
   (look-block-s :initarg :look-block-s :accessor look-block-s :initform 0)
   (look-block-e :initarg :look-block-e :accessor look-block-e :initform 0)
   (blocks-view-n :initarg :blocks-view-n :accessor blocks-view-n :initform 0)
   (blocks-view-w :initarg :blocks-view-w :accessor blocks-view-w :initform 0)
   (blocks-view-s :initarg :blocks-view-s :accessor blocks-view-s :initform 0)
   (blocks-view-e :initarg :blocks-view-e :accessor blocks-view-e :initform 0)
   (height-adj-pixels :initarg :height-adj-pixels :accessor height-adj-pixels :initform 0)
   (suppress-floor :initarg :suppress-floor :accessor suppress-floor :initform 0)
   (light-radius :initarg :light-radius :accessor light-radius :initform 0)
   (step-sound :initarg :step-sound :accessor step-sound :initform -1)
   (shortcut-key :initarg :shortcut-key :accessor shortcut-key)
   (crumble-type :initarg :crumble-type :accessor crumble-type :initform 0)
   (terrain-to-crumble-to :initarg :terrain-to-crumble-to :accessor terrain-to-crumble-to :initform 0)
   (beam-hit-type :initarg :beam-hit-type :accessor beam-hit-type :initform 0)
   (hidden-town-terrain :initarg :hidden-town-terrain :accessor hidden-town-terrain :initform -1)
   (swap-terrain :initarg :swap-terrain :accessor swap-terrain :initform -1)
   (is-bridge :initarg :is-bridge :accessor is-bridge :initform 0)
   (is-road :initarg :is-road :accessor is-road :initform 0)
   (can-look-at :initarg :can-look-at :accessor can-look-at :initform 0)
   (special-property :initarg :special-property :accessor special-property :initform 0)
   (special-strength :initarg :special-strength :accessor special-strength :initform 0)
   (draw-on-automap :initarg :draw-on-automap :accessor draw-on-automap :initform 0)
   (full-move-block :initarg :full-move-block :accessor full-move-block)
   (full-look-block :initarg :full-look-block :accessor full-look-block)
   (shimmers :initarg :shimmers :accessor shimmers :initform 0)
   (out-fight-town-used :initarg :out-fight-town-used :accessor out-fight-town-used :initform -1)))

(defclass creature ()
  ((name :initarg :name :accessor name)
   (default-script :initarg :default-script :accessor default-script :initform 0)
   (level :initarg :level :accessor level :initform 2)
   (hp-bonus :initarg :hp-bonus :accessor hp-bonus :initform 0)
   (sp-bonus :initarg :sp-bonus :accessor sp-bonus :initform 0)
   (special-abil :initarg :special-abil :accessor special-abil :initform 0)
   (default-attitude :initarg :default-attitude :accessor default-attitude :initform 2)
   (species :initarg :species :accessor species :initform 0)
   (natural-armor :initarg :natural-armor :accessor natural-armor :initform 0)
   (attack-1 :initarg :attack-1 :accessor attack-1 :initform 0)
   (attack-2 :initarg :attack-2 :accessor attack-2 :initform 0)
   (attack-3 :initarg :attack-3 :accessor attack-3 :initform 0)
   (attack-1-type :initarg :attack-1-type :accessor attack-1-type :initform 0)	
   (attack-23-type :initarg :attack-23-type :accessor attack-23-type :initform 0)
   (ap-bonus :initarg :ap-bonus :accessor ap-bonus :initform 0)
   (default-strategy :initarg :default-strategy :accessor default-strategy :initform 0)
   (default-aggression :initarg :default-aggression :accessor default-aggression :initform 100)
   (default-courage :initarg :default-courage :accessor default-courage :initform 100)
   (which-sheet :initarg :which-sheet :accessor which-sheet)
   (icon-adjust :initarg :icon-adjust :accessor icon-adjust :initform 0)
   (small-or-large-template :initarg :small-or-large-template :accessor small-or-large-template :initform 0)
   (which-sheet-upper :initarg :which-sheet-upper :accessor which-sheet-upper :initform -1)
   (summon-class :initarg :summon-class :accessor summon-class :initform -1)
   (what-stat-adjust :initarg :what-stat-adjust :accessor what-stat-adjust :initform (make-array 6 :initial-element -1 :element-type 'fixnum))
   (amount-stat-adjust :initarg :amount-stat-adjust :accessor amount-stat-adjust :initform (make-array 6 :initial-element -1 :element-type 'fixnum))
   (start-item :initarg :start-item :accessor start-item :initform (make-array 8 :initial-element -1 :element-type 'fixnum))
   (start-item-chance :initarg :start-item-chance :accessor start-item-chance :initform (make-array 8 :initial-element -1 :element-type 'fixnum))
   (immunities :initarg :immunities :accessor immunities :initform (make-array 6 :initial-element -1 :element-type 'fixnum))))

(defclass item ()
  ((name :initarg :name :accessor name)
   (full-name :initarg :full-name :accessor full-name)
   (variety :initarg :variety :accessor variety :initform 0)
   (damage-per-level :initarg :damage-per-level :accessor damage-per-level :initform 0)
   (bonus :initarg :bonus :accessor bonus :initform 0)
   (weapon-skill-used :initarg :weapon-skill-used :accessor weapon-skill-used :initform 4)
   (protection :initarg :protection :accessor protection :initform 0)
   (charges :initarg :charges :accessor charges :initform 0)
   (encumbrance :initarg :encumbrance :accessor encumbrance :initform 0)
   (floor-which-sheet :initarg :floor-which-sheet :accessor floor-which-sheet :initform 0)
   (floor-which-icon :initarg :floor-which-icon :accessor floor-which-icon :initform 0)
   (icon-adjust :initarg :icon-adjust :accessor icon-adjust)
   (inventory-icon :initarg :inventory-icon :accessor inventory-icon)
   (ability-1 :initarg :ability-1 :accessor ability-1 :initform -1)
   (ability-str-1 :initarg :ability-str-1 :accessor ability-str-1 :initform 0)
   (ability-2 :initarg :ability-2 :accessor ability-2 :initform -1)
   (ability-3 :initarg :ability-3 :accessor ability-3 :initform -1)
   (ability-4 :initarg :ability-4 :accessor ability-4 :initform -1)
   (ability-str-2 :initarg :ability-str-2 :accessor ability-str-2 :initform 0)
   (ability-str-3 :initarg :ability-str-3 :accessor ability-str-3 :initform 0)
   (ability-str-4 :initarg :ability-str-4 :accessor ability-str-4 :initform 0)
   (special-class :initarg :special-class :accessor special-class :initform 0)
   (value :initarg :value :accessor value :initform 0)
   (weight :initarg :weight :accessor weight :initform 0)
   (identified :initarg :identified :accessor identified :initform 0)
   (magic :initarg :magic :accessor magic :initform 0)
   (cursed :initarg :cursed :accessor cursed :initform 0)
   (once-per-day :initarg :once-per-day :accessor once-per-day :initform 0)
   (junk-item :initarg :junk-item :accessor junk-item :initform 0)
   (missile-anim-type :initarg :missile-anim-type :accessor missile-anim-type :initform 0)))